# Generated by Django 4.0.1 on 2022-01-30 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_customer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleorderline',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
